version: '3.1'

volumes:
  vol_ipt:

services:

  dnsmasq:
    image: andyshinn/dnsmasq:2.78
    command: --log-facility=- --server=172.16.0.12 --server=172.16.0.72 --server=127.0.0.11 --server=193.10.57.11 --server=8.8.8.8 --neg-ttl=3600 --cache-size=1000 --max-cache-ttl=3600 --min-cache-ttl=3600 --all-servers
    cap_add: 
      - NET_ADMIN 
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp
    links:
      - proxy:ipt.bioatlas.se
    depends_on:
      - proxy

  proxy:
    image: jwilder/nginx-proxy:alpine
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/bioatlas.conf && forego start -r"
    environment:
      - NGINX_MAX_BODY_SZ=200M
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - ./certs:/etc/nginx/certs
      - ./site.template:/etc/nginx/conf.d/site.template
    depends_on:
      - ipt

  ipt:
    image: bioatlas/ipt
    environment:
      - VIRTUAL_HOST=ipt.bioatlas.se
#      - JAVA_OPTS=-Xmx2g -Xms1g -XX:MaxPermSize=256m -Xss256k -Djava.awt.headless=true
    volumes:
      - vol_ipt:/usr/local/ipt

